export default {
  name: '虫',
  type: 'BUG',
  icon: 'https://nadokaciel.cn/public/uploads/15948896234504fvt.png',
  color: '#91C02E',
  colorDark: '#4C543F',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 0.5,
    FLYING: 0.5,
    POISON: 0.5,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 0.5,
    STEEL: 0.5,
    FIRE: 0.5,
    WATER: 1,
    GRASS: 2,
    ELECTRIC: 1,
    PSYCHIC: 2,
    ICE: 1,
    DRAGON: 1,
    DARK: 2,
    FAIRY: 0.5,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 0.5,
    FLYING: 2,
    POISON: 1,
    GROUND: 0.5,
    ROCK: 2,
    BUG: 1,
    GHOST: 1,
    STEEL: 1,
    FIRE: 2,
    WATER: 1,
    GRASS: 0.5,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};