export default {
  name: '恶',
  type: 'DARK',
  icon: 'https://nadokaciel.cn/public/uploads/1594889623495oxbb.png',
  color: '#5A5365',
  colorDark: '#44444A',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 0.5,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 2,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 2,
    ICE: 1,
    DRAGON: 1,
    DARK: 0.5,
    FAIRY: 0.5,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 2,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 2,
    GHOST: 0.5,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 0,
    ICE: 1,
    DRAGON: 1,
    DARK: 0.5,
    FAIRY: 2,
  },
};