export default {
  name: '龙',
  type: 'DRAGON',
  icon: 'https://nadokaciel.cn/public/uploads/1594889594992mbfz.png',
  color: '#0A6DC2',
  colorDark: '#364857',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 2,
    DARK: 1,
    FAIRY: 0,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 1,
    FIRE: 0.5,
    WATER: 0.5,
    GRASS: 0.5,
    ELECTRIC: 0.5,
    PSYCHIC: 1,
    ICE: 2,
    DRAGON: 2,
    DARK: 1,
    FAIRY: 2,
  },
};