export default {
  name: '电',
  type: 'ELECTRIC',
  icon: 'https://nadokaciel.cn/public/uploads/1594889623483blmd.png',
  color: '#F4D23C',
  colorDark: '#5D5941',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 2,
    POISON: 1,
    GROUND: 0,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 1,
    FIRE: 1,
    WATER: 2,
    GRASS: 0.5,
    ELECTRIC: 0.5,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 0.5,
    DARK: 1,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 0.5,
    POISON: 1,
    GROUND: 2,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 0.5,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};