export default {
  name: '妖精',
  type: 'FAIRY',
  icon: 'https://nadokaciel.cn/public/uploads/1594889595102254y.png',
  color: '#EB8FE6',
  colorDark: '#5D4E5D',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 2,
    FLYING: 1,
    POISON: 0.5,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 0.5,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 2,
    DARK: 2,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 0.5,
    FLYING: 1,
    POISON: 2,
    GROUND: 1,
    ROCK: 1,
    BUG: 0.5,
    GHOST: 1,
    STEEL: 2,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 0,
    DARK: 0.5,
    FAIRY: 1,
  },
};