export default {
  name: '格斗',
  type: 'FIGHTING',
  icon: 'https://nadokaciel.cn/public/uploads/1594889594985kl3e.png',
  color: '#CD406A',
  colorDark: '#57404A',
  atkMap: {
    NORMAL: 2,
    FIGHTING: 1,
    FLYING: 0.5,
    POISON: 0.5,
    GROUND: 1,
    ROCK: 2,
    BUG: 0.5,
    GHOST: 0,
    STEEL: 2,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 0.5,
    ICE: 2,
    DRAGON: 1,
    DARK: 2,
    FAIRY: 0.5,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 2,
    POISON: 1,
    GROUND: 1,
    ROCK: 0.5,
    BUG: 0.5,
    GHOST: 1,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 2,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 0.5,
    FAIRY: 2,
  },
};