export default {
  name: '火',
  type: 'FIRE',
  icon: 'https://nadokaciel.cn/public/uploads/1594889594990ivx1.png',
  color: '#FE9C54',
  colorDark: '#5F4F44',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 0.5,
    BUG: 2,
    GHOST: 1,
    STEEL: 2,
    FIRE: 0.5,
    WATER: 0.5,
    GRASS: 2,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 2,
    DRAGON: 0.5,
    DARK: 1,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 2,
    ROCK: 2,
    BUG: 0.5,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 0.5,
    WATER: 2,
    GRASS: 0.5,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 0.5,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};