export default {
  name: '飞行',
  type: 'FLYING',
  icon: 'https://nadokaciel.cn/public/uploads/1594889594978bsvx.png',
  color: '#8EA8DE',
  colorDark: '#4C525A',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 2,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 0.5,
    BUG: 2,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 1,
    WATER: 1,
    GRASS: 2,
    ELECTRIC: 0.5,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 0.5,
    FLYING: 1,
    POISON: 1,
    GROUND: 0,
    ROCK: 2,
    BUG: 0.5,
    GHOST: 1,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 0.5,
    ELECTRIC: 2,
    PSYCHIC: 1,
    ICE: 2,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};