export default {
  name: '幽灵',
  type: 'GHOST',
  icon: 'https://nadokaciel.cn/public/uploads/1594889595107cc3n.png',
  color: '#5269AC',
  colorDark: '#414852',
  atkMap: {
    NORMAL: 0,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 2,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 2,
    ICE: 1,
    DRAGON: 1,
    DARK: 0.5,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 0,
    FIGHTING: 0,
    FLYING: 1,
    POISON: 0.5,
    GROUND: 1,
    ROCK: 1,
    BUG: 0.5,
    GHOST: 2,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 2,
    FAIRY: 1,
  },
};