export default {
  name: '草',
  type: 'GRASS',
  icon: 'https://nadokaciel.cn/public/uploads/15948896234411f3w.png',
  color: '#62BB5A',
  colorDark: '#445447',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 0.5,
    POISON: 0.5,
    GROUND: 2,
    ROCK: 2,
    BUG: 0.5,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 0.5,
    WATER: 2,
    GRASS: 0.5,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 0.5,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 2,
    POISON: 2,
    GROUND: 0.5,
    ROCK: 1,
    BUG: 2,
    GHOST: 1,
    STEEL: 1,
    FIRE: 2,
    WATER: 0.5,
    GRASS: 0.5,
    ELECTRIC: 0.5,
    PSYCHIC: 1,
    ICE: 2,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};