export default {
  name: '地面',
  type: 'GROUND',
  icon: 'https://nadokaciel.cn/public/uploads/1594889623457olxj.png',
  color: '#D87844',
  colorDark: '#5A4A41',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 0,
    POISON: 2,
    GROUND: 1,
    ROCK: 2,
    BUG: 0.5,
    GHOST: 1,
    STEEL: 2,
    FIRE: 2,
    WATER: 1,
    GRASS: 0.5,
    ELECTRIC: 2,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 0.5,
    GROUND: 1,
    ROCK: 0.5,
    BUG: 1,
    GHOST: 1,
    STEEL: 1,
    FIRE: 1,
    WATER: 2,
    GRASS: 2,
    ELECTRIC: 0,
    PSYCHIC: 1,
    ICE: 2,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};