export default {
  name: '冰',
  type: 'ICE',
  icon: 'https://nadokaciel.cn/public/uploads/1594889623437zr97.png',
  color: '#73CEBF',
  colorDark: '#475757',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 2,
    POISON: 1,
    GROUND: 2,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 0.5,
    WATER: 0.5,
    GRASS: 2,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 0.5,
    DRAGON: 2,
    DARK: 1,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 2,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 2,
    BUG: 1,
    GHOST: 1,
    STEEL: 2,
    FIRE: 2,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 0.5,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};