export default {
  name: '毒',
  type: 'POISON',
  icon: 'https://nadokaciel.cn/public/uploads/1594889623488u2jv.png',
  color: '#A96AC8',
  colorDark: '#524857',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 0.5,
    GROUND: 0.5,
    ROCK: 0.5,
    BUG: 1,
    GHOST: 0.5,
    STEEL: 0,
    FIRE: 1,
    WATER: 1,
    GRASS: 2,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 2,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 0.5,
    FLYING: 1,
    POISON: 0.5,
    GROUND: 2,
    ROCK: 1,
    BUG: 0.5,
    GHOST: 1,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 0.5,
    ELECTRIC: 1,
    PSYCHIC: 2,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 0.5,
  },
};