export default {
  name: '超能',
  type: 'PSYCHIC',
  icon: 'https://nadokaciel.cn/public/uploads/15948896234441rig.png',
  color: '#F97178',
  colorDark: '#5D484A',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 2,
    FLYING: 1,
    POISON: 2,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 0.5,
    ICE: 1,
    DRAGON: 1,
    DARK: 0,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 0.5,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 2,
    GHOST: 2,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 0.5,
    ICE: 1,
    DRAGON: 1,
    DARK: 2,
    FAIRY: 1,
  },
};