export default {
  name: '岩石',
  type: 'ROCK',
  icon: 'https://nadokaciel.cn/public/uploads/159488959499678jj.png',
  color: '#C5B78B',
  colorDark: '#57544F',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 0.5,
    FLYING: 2,
    POISON: 1,
    GROUND: 0.5,
    ROCK: 1,
    BUG: 2,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 2,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 2,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 0.5,
    FIGHTING: 2,
    FLYING: 0.5,
    POISON: 0.5,
    GROUND: 2,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 2,
    FIRE: 0.5,
    WATER: 2,
    GRASS: 2,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};