export default {
  name: '钢',
  type: 'STEEL',
  icon: 'https://nadokaciel.cn/public/uploads/1594889594983fwz7.png',
  color: '#5A8DA1',
  colorDark: '#444C52',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 2,
    BUG: 1,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 0.5,
    WATER: 0.5,
    GRASS: 1,
    ELECTRIC: 0.5,
    PSYCHIC: 1,
    ICE: 2,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 2,
  },
  defMap: {
    NORMAL: 0.5,
    FIGHTING: 2,
    FLYING: 0.5,
    POISON: 0,
    GROUND: 2,
    ROCK: 0.5,
    BUG: 0.5,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 2,
    WATER: 1,
    GRASS: 0.5,
    ELECTRIC: 1,
    PSYCHIC: 0.5,
    ICE: 0.5,
    DRAGON: 0.5,
    DARK: 1,
    FAIRY: 0.5,
  },
};