export default {
  name: '？？？',
  type: 'UNKNOWN',
  icon: '',
  color: '#44685E',
  colorDark: '#44685E',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 1,
    FIRE: 1,
    WATER: 1,
    GRASS: 1,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};