export default {
  name: '水',
  type: 'WATER',
  icon: 'https://nadokaciel.cn/public/uploads/1594889594994w0hi.png',
  color: '#4F90D5',
  colorDark: '#414E5A',
  atkMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 2,
    ROCK: 2,
    BUG: 1,
    GHOST: 1,
    STEEL: 1,
    FIRE: 2,
    WATER: 0.5,
    GRASS: 0.5,
    ELECTRIC: 1,
    PSYCHIC: 1,
    ICE: 1,
    DRAGON: 0.5,
    DARK: 1,
    FAIRY: 1,
  },
  defMap: {
    NORMAL: 1,
    FIGHTING: 1,
    FLYING: 1,
    POISON: 1,
    GROUND: 1,
    ROCK: 1,
    BUG: 1,
    GHOST: 1,
    STEEL: 0.5,
    FIRE: 0.5,
    WATER: 0.5,
    GRASS: 2,
    ELECTRIC: 2,
    PSYCHIC: 1,
    ICE: 0.5,
    DRAGON: 1,
    DARK: 1,
    FAIRY: 1,
  },
};