export default {
  name: '风信子',
  seeds: ['rryyWw', 'rrYYWW', 'RRyyWw'],
  typeMap: {
    rryyWW: 'white',
    rryyWw: 'white',
    rryyww: 'blue',
    rrYyWW: 'yellow',
    rrYyWw: 'yellow',
    rrYyww: 'white',
    rrYYWW: 'yellow',
    rrYYWw: 'yellow',
    rrYYww: 'yellow',
    RryyWW: 'red',
    RryyWw: 'pink',
    Rryyww: 'white',
    RrYyWW: 'orange',
    RrYyWw: 'yellow',
    RrYyww: 'yellow',
    RrYYWW: 'orange',
    RrYYWw: 'yellow',
    RrYYww: 'yellow',
    RRyyWW: 'red',
    RRyyWw: 'red',
    RRyyww: 'red',
    RRYyWW: 'blue',
    RRYyWw: 'red',
    RRYyww: 'red',
    RRYYWW: 'violet',
    RRYYWw: 'violet',
    RRYYww: 'violet',
  },
  routeMap: {
    orange: [{
      parent1: 'rrYYWW',
      parent2: 'RRyyWw',
      son: 'RrYyWW',
    }],
    blue: [{
      parent1: 'rryyWw',
      parent2: 'rryyWw',
      son: 'rryyww',
    }],
    pink: [{
      parent1: 'rryyWw',
      parent2: 'RRyyWw',
      son: 'RryyWw',
    }],
    violet: [{
      parent1: 'rrYYWW',
      parent2: 'RRyyWw',
      son: 'RrYyWW',
    }, {
      parent1: 'RrYyWW',
      parent2: 'RrYyWW',
      son: 'RRYYWW',
      hint: '橙色的蓝色、橙色后代也可保留，自交或杂交出紫色风信子的概率更高',
    }, {
      parent1: 'RrYyWW',
      parent2: 'RrYyWW',
      son: 'RRYyWW',
    }, {
      parent1: 'RrYyWW',
      parent2: 'RrYyWW',
      son: 'RrYYWW',
    }, {
      parent1: 'RrYyWW',
      parent2: 'RRYyWW',
      son: 'RRYYWW',
      hint: '一代橙与蓝色后代杂交',
    }, {
      parent1: 'RrYyWW',
      parent2: 'RrYYWW',
      son: 'RRYYWW',
      hint: '一代橙与橙色后代杂交',
    }, {
      parent1: 'RRYyWW',
      parent2: 'RrYYWW',
      son: 'RRYYWW',
      hint: '蓝色与橙色后代杂交',
    }, {
      parent1: 'RRYyWW',
      parent2: 'RRYyWW',
      son: 'RRYYWW',
      hint: '蓝色后代自交',
    }, {
      parent1: 'RrYYWW',
      parent2: 'RrYYWW',
      son: 'RRYYWW',
      hint: '橙色后代自交',
    }],
  },
  imageMap: {
    white: 'http://120.27.3.78:3000/public/uploads/15875415495471z53.png',
    yellow: 'http://120.27.3.78:3000/public/uploads/1587541549545wbjl.png',
    red: 'http://120.27.3.78:3000/public/uploads/15875415495577rsq.png',
    orange: 'http://120.27.3.78:3000/public/uploads/1587541549626st5k.png',
    blue: 'http://120.27.3.78:3000/public/uploads/1587541549550ncd0.png',
    pink: 'http://120.27.3.78:3000/public/uploads/1587541549541mtx1.png',
    violet: 'http://120.27.3.78:3000/public/uploads/1587541549544oyew.png',
  },
};