export default {
  name: '菊花',
  seeds: ['rryyWw', 'rrYYWW', 'RRyyWW'],
  typeMap: {
    rryyWW: 'white',
    rryyWw: 'white',
    rryyww: 'violet',
    rrYyWW: 'yellow',
    rrYyWw: 'yellow',
    rrYyww: 'white',
    rrYYWW: 'yellow',
    rrYYWw: 'yellow',
    rrYYww: 'yellow',
    RryyWW: 'pink',
    RryyWw: 'pink',
    Rryyww: 'pink',
    RrYyWW: 'yellow',
    RrYyWw: 'red',
    RrYyww: 'pink',
    RrYYWW: 'violet',
    RrYYWw: 'violet',
    RrYYww: 'violet',
    RRyyWW: 'red',
    RRyyWw: 'red',
    RRyyww: 'red',
    RRYyWW: 'violet',
    RRYyWw: 'violet',
    RRYyww: 'red',
    RRYYWW: 'green',
    RRYYWw: 'green',
    RRYYww: 'red',
  },
  routeMap: {
    pink: [{
      parent1: 'rryyWw',
      parent2: 'RRyyWW',
      son: 'RryyWW',
    }, {
      parent1: 'rryyWw',
      parent2: 'RRyyWW',
      son: 'RryyWw',
    }],
    violet: [{
      parent1: 'rryyWw',
      parent2: 'rryyWw',
      son: 'rryyww',
    }],
    green: [{
      parent1: 'rrYYWW',
      parent2: 'RRyyWW',
      son: 'RrYyWW',
    }, {
      parent1: 'RrYyWW',
      parent2: 'RrYyWW',
      son: 'RRYYWW',
      hint: '二代黄的紫色后代也可保留，紫色自交或与二代黄出绿色菊花的概率更高',
    }, {
      parent1: 'RrYyWW',
      parent2: 'RrYyWW',
      son: 'RrYYWW',
    }, {
      parent1: 'RrYYWW',
      parent2: 'RrYyWW',
      son: 'RRYYWW',
    }, {
      parent1: 'RrYYWW',
      parent2: 'RrYYWW',
      son: 'RRYYWW',
    }],
  },
  imageMap: {
    white: 'https://nadokaciel.cn/public/uploads/1587540846513f6aa.png',
    yellow: 'https://nadokaciel.cn/public/uploads/1587540846507snhw.png',
    red: 'https://nadokaciel.cn/public/uploads/1587540846521pwef.png',
    pink: 'https://nadokaciel.cn/public/uploads/15875408465150dyi.png',
    violet: 'https://nadokaciel.cn/public/uploads/1587540846505whli.png',
    green: 'https://nadokaciel.cn/public/uploads/1587540846518ogrs.png',
  },
};