export default {
  name: '玫瑰',
  seeds: ['rryyWwss', 'rrYYWWss', 'RRyyWWSs'],
  typeMap: {
    rryyWWss: 'white',
    rryyWWSs: 'white',
    rryyWWSS: 'white',
    rryyWwss: 'white',
    rryyWwSs: 'white',
    rryyWwSS: 'white',
    rryywwss: 'violet',
    rryywwSs: 'violet',
    rryywwSS: 'violet',
    rrYyWWss: 'yellow',
    rrYyWWSs: 'yellow',
    rrYyWWSS: 'yellow',
    rrYyWwss: 'white',
    rrYyWwSs: 'white',
    rrYyWwSS: 'white',
    rrYywwss: 'violet',
    rrYywwSs: 'violet',
    rrYywwSS: 'violet',
    rrYYWWss: 'yellow',
    rrYYWWSs: 'yellow',
    rrYYWWSS: 'yellow',
    rrYYWwss: 'yellow',
    rrYYWwSs: 'yellow',
    rrYYWwSS: 'yellow',
    rrYYwwss: 'white',
    rrYYwwSs: 'white',
    rrYYwwSS: 'white',
    RryyWWss: 'red',
    RryyWWSs: 'pink',
    RryyWWSS: 'white',
    RryyWwss: 'red',
    RryyWwSs: 'pink',
    RryyWwSS: 'white',
    Rryywwss: 'red',
    RryywwSs: 'pink',
    RryywwSS: 'violet',
    RrYyWWss: 'orange',
    RrYyWWSs: 'yellow',
    RrYyWWSS: 'yellow',
    RrYyWwss: 'red',
    RrYyWwSs: 'pink',
    RrYyWwSS: 'white',
    RrYywwss: 'red',
    RrYywwSs: 'pink',
    RrYywwSS: 'violet',
    RrYYWWss: 'orange',
    RrYYWWSs: 'yellow',
    RrYYWWSS: 'yellow',
    RrYYWwss: 'orange',
    RrYYWwSs: 'yellow',
    RrYYWwSS: 'yellow',
    RrYYwwss: 'red',
    RrYYwwSs: 'pink',
    RrYYwwSS: 'white',
    RRyyWWss: 'dark',
    RRyyWWSs: 'red',
    RRyyWWSS: 'pink',
    RRyyWwss: 'dark',
    RRyyWwSs: 'red',
    RRyyWwSS: 'pink',
    RRyywwss: 'dark',
    RRyywwSs: 'red',
    RRyywwSS: 'pink',
    RRYyWWss: 'orange',
    RRYyWWSs: 'orange',
    RRYyWWSS: 'yellow',
    RRYyWwss: 'red',
    RRYyWwSs: 'red',
    RRYyWwSS: 'white',
    RRYywwss: 'dark',
    RRYywwSs: 'red',
    RRYywwSS: 'violet',
    RRYYWWss: 'orange',
    RRYYWWSs: 'orange',
    RRYYWWSS: 'yellow',
    RRYYWwss: 'orange',
    RRYYWwSs: 'orange',
    RRYYWwSS: 'yellow',
    RRYYwwss: 'blue',
    RRYYwwSs: 'red',
    RRYYwwSS: 'white',
  },
  routeMap: {
    violet: [{
      parent1: 'rryyWwss',
      parent2: 'rryyWwss',
      son: 'rryywwss',
    }],
    orange: [{
      parent1: 'rrYYWWss',
      parent2: 'RRyyWWSs',
      son: 'RrYyWWss',
    }],
    pink: [{
      parent1: 'rryyWwss',
      parent2: 'RRyyWWSs',
      son: 'RryyWWSs',
    }, {
      parent1: 'rryyWwss',
      parent2: 'RRyyWWSs',
      son: 'RryyWwSs',
    }],
    dark: [{
      parent1: 'RRyyWWSs',
      parent2: 'RRyyWWSs',
      son: 'RRyyWWss',
    }],
    gold: [{
      parent1: 'RRyyWWSs',
      parent2: 'RRyyWWSs',
      son: 'RRyyWWss',
      hint: '用金色浇水壶浇过的黑色玫瑰可自交出金色玫瑰',
    }],
    // blue: [{
    //   parent1: 'rryyWwss',
    //   parent2: 'rryyWwss',
    //   son: 'rryywwss',
    // }, {
    //   parent1: 'rrYYWWss',
    //   parent2: 'RRyyWWSs',
    //   son: 'RrYyWWss',
    // }, {
    //   parent1: 'rryywwss',
    //   parent2: 'RrYyWWss',
    //   son: 'RrYyWwss',
    // }, {
    //   parent1: 'RrYyWwss',
    //   parent2: 'RrYyWwss',
    //   son: 'RRYYwwss',
    // }],
    blue: [{
      parent1: 'rryyWwss',
      parent2: 'rryyWwss',
      son: 'rryywwss',
    }, {
      parent1: 'rryyWwss',
      parent2: 'rrYYWWss',
      son: 'rrYyWwss',
      hint: '这里杂交出的白色后代都可使用',
    }, {
      parent1: 'rryywwss',
      parent2: 'rrYyWwss',
      son: 'rrYywwss',
      hint: '这里杂交出的紫色后代有一半不可用，但在第五步紫橙杂交时可放心辨别',
    }, {
      parent1: 'rrYYWWss',
      parent2: 'RRyyWWSs',
      son: 'RrYyWWss',
    }, {
      parent1: 'rrYywwss',
      parent2: 'RrYyWWss',
      son: 'RrYYWwss',
      hint: '若长期无法产出橙色后代，需替换或扩大第三步紫色后代的使用',
    }, {
      parent1: 'RrYYWwss',
      parent2: 'RrYYWwss',
      son: 'RRYYwwss',
      hint: '这里已经可以产出蓝色玫瑰，也可继续使用后代红',
    }, {
      parent1: 'RrYYWwss',
      parent2: 'RrYYWwss',
      son: 'RrYYwwss',
      hint: '这里的红色后代全是安全颜色，基因型统一',
    }, {
      parent1: 'RrYYwwss',
      parent2: 'RrYYwwss',
      son: 'RRYYwwss',
      hint: '此时蓝色玫瑰的产出概率为最高',
    }],
  },
  imageMap: {
    white: 'https://nadokaciel.cn/public/uploads/1587542694466o45x.png',
    yellow: 'https://nadokaciel.cn/public/uploads/1587542694456em0p.png',
    red: 'https://nadokaciel.cn/public/uploads/1587542694464iujk.png',
    orange: 'https://nadokaciel.cn/public/uploads/1587542694539ys44.png',
    blue: 'https://nadokaciel.cn/public/uploads/1587542694522637p.png',
    pink: 'https://nadokaciel.cn/public/uploads/15875426944513pft.png',
    dark: 'https://nadokaciel.cn/public/uploads/1587542694451437d.png',
    violet: 'https://nadokaciel.cn/public/uploads/1587542694535e0dh.png',
    gold: 'https://nadokaciel.cn/public/uploads/1587542694468fxxe.png',
  },
};