export default {
  name: '银莲花',
  seeds: ['rrooWw', 'rrOOWW', 'RRooWW'],
  typeMap: {
    rrooWW: 'white',
    rrooWw: 'white',
    rrooww: 'blue',
    rrOoWW: 'orange',
    rrOoWw: 'orange',
    rrOoww: 'blue',
    rrOOWW: 'orange',
    rrOOWw: 'orange',
    rrOOww: 'orange',
    RrooWW: 'red',
    RrooWw: 'red',
    Rrooww: 'blue',
    RrOoWW: 'pink',
    RrOoWw: 'pink',
    RrOoww: 'pink',
    RrOOWW: 'orange',
    RrOOWw: 'orange',
    RrOOww: 'orange',
    RRooWW: 'red',
    RRooWw: 'red',
    RRooww: 'violet',
    RROoWW: 'red',
    RROoWw: 'red',
    RROoww: 'violet',
    RROOWW: 'pink',
    RROOWw: 'pink',
    RROOww: 'violet',
  },
  routeMap: {
    blue: [{
      parent1: 'rrooWw',
      parent2: 'rrooWw',
      son: 'rrooww',
    }],
    pink: [{
      parent1: 'rrOOWW',
      parent2: 'RRooWW',
      son: 'RrOoWW',
    }],
    violet: [{
      parent1: 'rrOOWW',
      parent2: 'RRooWW',
      son: 'RrOoWW',
    }, {
      parent1: 'RrOoWW',
      parent2: 'rrooWw',
      son: 'RrOoWw',
    }, {
      parent1: 'RrOoWw',
      parent2: 'RrOoWw',
      son: 'RROoww',
    }, {
      parent1: 'RrOoWw',
      parent2: 'RrOoWw',
      son: 'RROOww',
    }],
  },
  imageMap: {
    white: 'https://nadokaciel.cn/public/uploads/1587541155964gtvv.png',
    red: 'https://nadokaciel.cn/public/uploads/1587541155958b2pk.png',
    orange: 'https://nadokaciel.cn/public/uploads/15875411559718b19.png',
    blue: 'https://nadokaciel.cn/public/uploads/1587541155972ggy8.png',
    pink: 'https://nadokaciel.cn/public/uploads/15875411559612p41.png',
    violet: 'https://nadokaciel.cn/public/uploads/1587541155956vz0a.png',
  },
};